### ISSUE TITLE
could you provide a status of this project ?

### ISSUE THREAD

**Issue by devZer0** [baycom/tfrec#12]
i'd be happy to know about the current status of this project, as https://github.com/baycom/tfrec/issues/7  did not get a reply

**Comment by baycom** [comment]
It's a side project, started just as a reverse engineering fiddling for my KlimaLogPro sensors. Support for other sensors went in just by accident ;) I currently do not have the time to do bigger developments on tfrec.

**Comment by devZer0** [comment]
thanks for the info, you can close this ticket
