### ISSUE TITLE
unknown weatherhub sensor TFA 30.3300.02 (temp only)

### ISSUE THREAD

**Issue by flcu** [baycom/tfrec#13]
Hi
I have a "plain" Temperature TFA Weatherhub sensor.
#000 1550170800 L=25  4b 2d d4 2b 12 02 48 97 a9 de 8a 40 00 81 13 00 fa 00 27 dd 68 b2 30 c0 06  RSSI 80 WHB: Probably unsupported sensor type 02! Please report

WHB BAD 1 RSSI 80 (SANITY)
#001 1550170800 L=25  4b 2d d4 2b 12 02 48 97 a9 de 8a 40 00 81 13 00 fa 00 27 dd 68 b2 30 c0 06  RSSI 80 WHB: Probably unsupported sensor type 02! Please report

WHB BAD 2 RSSI 80 (SANITY)
#002 1550170801 L=25  4b 2d d4 2b 12 02 48 97 a9 de 8a 40 00 81 13 00 fa 00 27 dd 68 b2 30 c0 06  RSSI 80 WHB: Probably unsupported sensor type 02! Please report

WHB BAD 3 RSSI 80 (SANITY)
#003 1550170801 L=25  4b 2d d4 2b 12 02 48 97 a9 de 8a 40 00 81 13 00 fa 00 27 dd 68 b2 30 c0 06  RSSI 80 WHB: Probably unsupported sensor type 02! Please report

Can you add a decoder for it?

**Comment by baycom** [comment]
Should be supported  now, please check.

**Comment by flcu** [comment]
Yes, it does, I can confirm that I get the temperature back.
Thank you very much!
